[package]
name = 'AptosGame'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = 'main'
subdir = "aptos-move/framework/aptos-stdlib/"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = 'main'
subdir = "aptos-move/framework/aptos-token/"

[addresses]
GameDeployer = "_"
